football_2023 = {
    "conference": [
        "Conference USA football standings",
        "Conference USA football standings",
        "NCAA Division I FBS independents",
        "NCAA Division I FBS independents",
        "Mountain West",
        "Pac-12",
        "Southeastern",
        "Big 12",
        "Big Ten",
        "Atlantic Coast",
        "Pac-12",
        "Atlantic Coast",
        "Atlantic Coast",
        "Big Ten",
        "Pac-12",
        "Southeastern",
        "Southeastern",
        "Big 12",
        "Pac-12",
        "Pac-12",
        "Mountain West",
        "Big 12",
        "Big Ten",
        "Big Ten",
        "Southeastern",
        "Conference USA football standings",
        "Sun Belt",
        "Big Ten",
        "Atlantic Coast",
        "Mid-American",
        "Big Ten",
        "Big 12",
        "Big Ten",
        "American Athletic",
        "Southeastern",
        "Big 12",
        "Southeastern",
        "Sun Belt",
        "American Athletic",
        "Pac-12",
        "Atlantic Coast",
        "Pac-12",
        "Pac-12",
        "Conference USA football standings",
        "Big Ten",
        "Mountain West",
        "Atlantic Coast",
        "Pac-12",
        "Big Ten",
        "Atlantic Coast",
        "Big 12",
        "Mountain West",
        "Southeastern",
        "Big 12",
        "Sun Belt",
        "Conference USA football standings",
        "Southeastern",
        "Sun Belt",
        "Sun Belt",
        "Sun Belt",
        "Big 12",
        "Sun Belt",
        "Big Ten",
        "American Athletic",
        "Mid-American",
        "Southeastern",
        "Southeastern",
        "Southeastern",
        "Big Ten",
        "Mid-American",
        "Big 12",
        "Sun Belt",
        "Pac-12",
        "Big Ten",
        "American Athletic",
        "Atlantic Coast",
        "American Athletic",
        "Atlantic Coast",
        "NCAA Division I FBS independents",
        "Sun Belt",
        "Pac-12",
        "Atlantic Coast",
        "Mid-American",
        "Southeastern",
        "Sun Belt",
        "Southeastern",
        "Big Ten",
        "Mountain West",
        "Conference USA football standings",
        "American Athletic",
        "Sun Belt",
        "Big 12",
        "Mid-American",
        "Big 12",
        "Mountain West",
        "Sun Belt",
        "Mid-American",
        "Mountain West",
        "Atlantic Coast",
        "Big Ten",
        "Big 12",
        "Mountain West",
        "Southeastern",
        "American Athletic",
        "Sun Belt",
        "American Athletic",
        "Mountain West",
        "Big 12",
        "Atlantic Coast",
        "Mid-American",
        "Mid-American",
        "Big 12",
        "Mountain West",
        "Mid-American",
        "American Athletic",
        "NCAA Division I FBS independents",
        "American Athletic",
        "American Athletic",
        "Conference USA football standings",
        "Conference USA football standings",
        "Atlantic Coast",
        "Mountain West",
        "Mid-American",
        "American Athletic",
        "Mountain West",
        "Atlantic Coast",
        "Pac-12",
        "Mid-American",
        "Sun Belt",
        "American Athletic",
        "Conference USA football standings",
        "Mid-American"
    ],
    "conference_standing": [
        "Conference USA football standings",
        "Conference USA football standings",
        "NCAA Division I FBS independents",
        "NCAA Division I FBS independents",
        "Mountain West",
        "Pac-12",
        "Southeastern (East)",
        "Big 12",
        "Big Ten (West)",
        "Atlantic Coast",
        "Pac-12",
        "Atlantic Coast",
        "Atlantic Coast",
        "Big Ten (East)",
        "Pac-12",
        "Southeastern (West)",
        "Southeastern (West)",
        "Big 12",
        "Pac-12",
        "Pac-12",
        "Mountain West",
        "Big 12",
        "Big Ten (West)",
        "Big Ten (West)",
        "Southeastern (East)",
        "Conference USA football standings",
        "Sun Belt (West)",
        "Big Ten (East)",
        "Atlantic Coast",
        "Mid-American (West)",
        "Big Ten (East)",
        "Big 12",
        "Big Ten (East)",
        "American Athletic",
        "Southeastern (East)",
        "Big 12",
        "Southeastern (West)",
        "Sun Belt (West)",
        "American Athletic",
        "Pac-12",
        "Atlantic Coast",
        "Pac-12",
        "Pac-12",
        "Conference USA football standings",
        "Big Ten (West)",
        "Mountain West",
        "Atlantic Coast",
        "Pac-12",
        "Big Ten (East)",
        "Atlantic Coast",
        "Big 12",
        "Mountain West",
        "Southeastern (West)",
        "Big 12",
        "Sun Belt (East)",
        "Conference USA football standings",
        "Southeastern (East)",
        "Sun Belt (East)",
        "Sun Belt (East)",
        "Sun Belt (East)",
        "Big 12",
        "Sun Belt (East)",
        "Big Ten (East)",
        "American Athletic",
        "Mid-American (East)",
        "Southeastern (West)",
        "Southeastern (West)",
        "Southeastern (East)",
        "Big Ten (West)",
        "Mid-American (East)",
        "Big 12",
        "Sun Belt (East)",
        "Pac-12",
        "Big Ten (West)",
        "American Athletic",
        "Atlantic Coast",
        "American Athletic",
        "Atlantic Coast",
        "NCAA Division I FBS independents",
        "Sun Belt (East)",
        "Pac-12",
        "Atlantic Coast",
        "Mid-American (West)",
        "Southeastern (East)",
        "Sun Belt (West)",
        "Southeastern (West)",
        "Big Ten (West)",
        "Mountain West",
        "Conference USA football standings",
        "American Athletic",
        "Sun Belt (West)",
        "Big 12",
        "Mid-American (West)",
        "Big 12",
        "Mountain West",
        "Sun Belt (West)",
        "Mid-American (West)",
        "Mountain West",
        "Atlantic Coast",
        "Big Ten (East)",
        "Big 12",
        "Mountain West",
        "Southeastern (East)",
        "American Athletic",
        "Sun Belt (West)",
        "American Athletic",
        "Mountain West",
        "Big 12",
        "Atlantic Coast",
        "Mid-American (East)",
        "Mid-American (East)",
        "Big 12",
        "Mountain West",
        "Mid-American (West)",
        "American Athletic",
        "NCAA Division I FBS independents",
        "American Athletic",
        "American Athletic",
        "Conference USA football standings",
        "Conference USA football standings",
        "Atlantic Coast",
        "Mountain West",
        "Mid-American (West)",
        "American Athletic",
        "Mountain West",
        "Atlantic Coast",
        "Pac-12",
        "Mid-American (East)",
        "Sun Belt (West)",
        "American Athletic",
        "Conference USA football standings",
        "Mid-American (East)"
    ]
}
